version: "2"
run:
  concurrency: 4
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  enable:
    - copyloopvar
    - decorder
    - errorlint
    - exhaustive
    - gocritic
    - gosec
    - misspell
    - predeclared
    - reassign
    - revive
    - testifylint
    - unconvert
    - unparam
    - wastedassign
  settings:
    exhaustive:
      explicit-exhaustive-switch: true
    govet:
      disable:
        - fieldalignment
        - loopclosure
      enable-all: true
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    misspell:
      locale: US
      ignore-rules:
        - cancelled
        - metre
        - meter
        - metres
        - kilometre
        - kilometres
    predeclared:
      ignore:
        - copy
    revive:
      confidence: 0.8
    testifylint:
      enable-all: true
      disable:
        - float-compare
        - require-error
        - suite-subtest-run
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        text: 'G404:'
      - linters:
          - gosec
        text: 'G402:'
    paths:
      - signalfx
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/splunk-terraform/terraform-provider-signalfx)
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: interface{}
          replacement: any
    goimports:
      local-prefixes:
        - github.com/splunk-terraform/terraform-provider-signalfx
  exclusions:
    generated: lax
    paths:
      - signalfx
      - third_party$
      - builtin$
      - examples$
