// Copyright Splunk, Inc.
// SPDX-License-Identifier: MPL-2.0

package fwintegration

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/signalfx/signalfx-go/integration"

	fwembed "github.com/splunk-terraform/terraform-provider-signalfx/internal/framework/embed"
	"github.com/splunk-terraform/terraform-provider-signalfx/internal/framework/fwerr"
)

type ResourceAWSExternal struct {
	fwembed.ResourceData
}

type resourceAWSExternalModel struct {
	awsBootstrapModel
	ExternalID types.String `tfsdk:"external_id"`
}

var (
	_ resource.Resource              = (*ResourceAWSExternal)(nil)
	_ resource.ResourceWithConfigure = (*ResourceAWSExternal)(nil)
)

func NewResourceAWSExternal() resource.Resource {
	return &ResourceAWSExternal{}
}

func (awsExternal *ResourceAWSExternal) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_aws_external_integration"
}

func (awsExternal *ResourceAWSExternal) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	attributes := awsBootstrapAttributes()
	attributes["external_id"] = schema.StringAttribute{
		Computed:    true,
		Sensitive:   true,
		Description: "AWS external ID generated by Splunk Observability Cloud for the AWS role.",
	}

	resp.Schema = schema.Schema{
		Description: "Bootstraps an AWS CloudWatch integration using an external ID. Complete the workflow with signalfx_aws_integration.",
		Attributes:  attributes,
	}
}

func (awsExternal *ResourceAWSExternal) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var model resourceAWSExternalModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &model)...)
	if resp.Diagnostics.HasError() {
		return
	}

	details, err := awsExternal.Details().Client.CreateAWSCloudWatchIntegration(
		ctx,
		model.awsIntegration(integration.EXTERNAL_ID),
	)
	if resp.Diagnostics.Append(fwerr.ErrorHandler(ctx, resp.State, withAdminTokenHelp(err))...); resp.Diagnostics.HasError() {
		return
	}
	if details == nil {
		resp.Diagnostics.AddError("Missing AWS integration response", "Splunk Observability Cloud returned no AWS integration after creation.")
		return
	}

	model.updateFromAPI(details, true)
	resp.Diagnostics.Append(resp.State.Set(ctx, &model)...)
}

func (awsExternal *ResourceAWSExternal) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var model resourceAWSExternalModel
	resp.Diagnostics.Append(req.State.Get(ctx, &model)...)
	if resp.Diagnostics.HasError() {
		return
	}

	details, err := awsExternal.Details().Client.GetAWSCloudWatchIntegration(ctx, model.ID.ValueString())
	if resp.Diagnostics.Append(fwerr.ErrorHandler(ctx, resp.State, err)...); resp.Diagnostics.HasError() {
		return
	}
	if details == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	model.updateFromAPI(details, false)
	resp.Diagnostics.Append(resp.State.Set(ctx, &model)...)
}

func (*ResourceAWSExternal) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan resourceAWSExternalModel
	var current resourceAWSExternalModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &current)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// All configurable fields require replacement. Retain generated values if
	// the Framework invokes Update solely for a state-only transition.
	plan.ID = current.ID
	plan.ExternalID = current.ExternalID
	plan.SignalFxAWSAccount = current.SignalFxAWSAccount
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (*ResourceAWSExternal) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var model resourceAWSExternalModel
	resp.Diagnostics.Append(req.State.Get(ctx, &model)...)
	// Deletion is intentionally owned by signalfx_aws_integration. Returning
	// without diagnostics removes this bootstrap resource from Terraform state.
}

func (model *resourceAWSExternalModel) updateFromAPI(details *integration.AwsCloudWatchIntegration, updateIdentity bool) {
	if details == nil {
		return
	}

	model.awsBootstrapModel.updateFromAPI(details, updateIdentity)
	if details.AuthMethod == integration.EXTERNAL_ID && details.ExternalId != "" {
		model.ExternalID = types.StringValue(details.ExternalId)
	}
}
